In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
data = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv"
df = pd.read_csv(data)
df.head()

,lead_source,industry,number_of_courses_viewed,annual_income,employment_status,location,interaction_count,lead_score,converted
0,paid_ads,NaN,1,79450.0,unemployed,south_america,4,0.94,1
1,social_media,retail,1,46992.0,employed,south_america,1,0.80,0
2,events,healthcare,5,78796.0,unemployed,australia,3,0.69,1
3,paid_ads,retail,2,83843.0,NaN,australia,1,0.87,0
4,referral,education,3,85012.0,self_employed,europe,3,0.62,1

## In this dataset our desired target for classification task will be converted variable - has the client signed up to the platform or not.

### Data Preparation

In [6]:
# If there are missing values:
print(df.dtypes)
df.isna().sum() #For caterogiral features, replace them with 'NA' and For numerical features, replace with with 0.0

lead_source                  object
industry                     object
number_of_courses_viewed      int64
annual_income               float64
employment_status            object
location                     object
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

lead_source                 128
industry                    134
number_of_courses_viewed      0
annual_income               181
employment_status           100
location                     63
interaction_count             0
lead_score                    0
converted                     0
dtype: int64

In [13]:
# Fill object (string) columns with "NA"
df[df.select_dtypes(include="object").columns] = (
    df.select_dtypes(include="object").fillna("NA")
)

# Fill numeric columns with 0
df[df.select_dtypes(exclude="object").columns] = (
    df.select_dtypes(exclude="object").fillna(0)
)
df.isna().sum()

lead_source                 0
industry                    0
number_of_courses_viewed    0
annual_income               0
employment_status           0
location                    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

### Question 1
What is the most frequent observation (mode) for the column industry?

In [17]:
list(df["industry"].value_counts().sort_values(ascending=False).head(1).index)

['retail']

### Question 2
Create the correlation matrix for the numerical features of your dataset.<br>
In a correlation matrix, you compute the correlation coefficient between every pair of features.<br>
What are the two features that have the biggest correlation?

In [27]:
df_corr = df.select_dtypes(exclude="object")
corr_data = df_corr.corr()
#Heatmap plotting
# sns.heatmap(corr_data,cmap="coolwarm",annot=True)
print('Answer from the considering the question is annual_income and interaction_count')
display(corr_data)

Answer from the considering the question is annual_income and interaction_count

,number_of_courses_viewed,annual_income,interaction_count,lead_score,converted
number_of_courses_viewed,1.000000,0.009770,-0.023565,-0.004879,0.435914
annual_income,0.009770,1.000000,0.027036,0.015610,0.053131
interaction_count,-0.023565,0.027036,1.000000,0.009888,0.374573
lead_score,-0.004879,0.015610,0.009888,1.000000,0.193673
converted,0.435914,0.053131,0.374573,0.193673,1.000000

Split the data
- Split your data in train/val/test sets with 60%/20%/20% distribution.
- Use Scikit-Learn for that (the train_test_split function) and set the seed to 42.
- Make sure that the target value y is not in your dataframe.

### Question 3
- Calculate the mutual information score between y and other categorical variables in the dataset. Use the training set only.
- Round the scores to 2 decimals using round(score, 2).

### Question 4
- Now let's train a logistic regression.
- Remember that we have several categorical variables in the dataset. Include them using one-hot encoding.
- Fit the model on the training dataset.
  - To make sure the results are reproducible across different versions of Scikit-Learn, fit the model with these parameters:<br>
      `model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)`
- Calculate the accuracy on the validation dataset and round it to 2 decimal digits.<br>
What accuracy did you get?

### Question 5
- Let's find the least useful feature using the feature elimination technique.
- Train a model using the same features and parameters as in Q4 (without rounding).
- Now exclude each feature from this set and train a model without it. Record the accuracy for each model.
- For each feature, calculate the difference between the original accuracy and the accuracy without the feature.

### Question 6
- Now let's train a regularized logistic regression.
- Let's try the following values of the parameter `C: [0.01, 0.1, 1, 10, 100].`
- Train models using all the features as in Q4.
- Calculate the accuracy on the validation dataset and round it to 3 decimal digits